
# Eagler Context Redacted Diff
# Copyright (c) 2026 lax1dude. All rights reserved.

# Version: 1.0
# Author: lax1dude

> DELETE  34  @  34 : 35

> CHANGE  3 : 373  @  3 : 201

~ 	public static Block air;
~ 	public static Block stone;
~ 	public static BlockGrass grass;
~ 	public static Block dirt;
~ 	public static Block cobblestone;
~ 	public static Block planks;
~ 	public static Block sapling;
~ 	public static Block bedrock;
~ 	public static BlockDynamicLiquid flowing_water;
~ 	public static BlockStaticLiquid water;
~ 	public static BlockDynamicLiquid flowing_lava;
~ 	public static BlockStaticLiquid lava;
~ 	public static BlockSand sand;
~ 	public static Block gravel;
~ 	public static Block gold_ore;
~ 	public static Block iron_ore;
~ 	public static Block coal_ore;
~ 	public static Block log;
~ 	public static Block log2;
~ 	public static BlockLeaves leaves;
~ 	public static BlockLeaves leaves2;
~ 	public static Block sponge;
~ 	public static Block glass;
~ 	public static Block lapis_ore;
~ 	public static Block lapis_block;
~ 	public static Block dispenser;
~ 	public static Block sandstone;
~ 	public static Block noteblock;
~ 	public static Block bed;
~ 	public static Block golden_rail;
~ 	public static Block detector_rail;
~ 	public static BlockPistonBase sticky_piston;
~ 	public static Block web;
~ 	public static BlockTallGrass tallgrass;
~ 	public static BlockDeadBush deadbush;
~ 	public static BlockPistonBase piston;
~ 	public static BlockPistonExtension piston_head;
~ 	public static Block wool;
~ 	public static BlockPistonMoving piston_extension;
~ 	public static BlockFlower yellow_flower;
~ 	public static BlockFlower red_flower;
~ 	public static BlockBush brown_mushroom;
~ 	public static BlockBush red_mushroom;
~ 	public static Block gold_block;
~ 	public static Block iron_block;
~ 	public static BlockSlab double_stone_slab;
~ 	public static BlockSlab stone_slab;
~ 	public static Block brick_block;
~ 	public static Block tnt;
~ 	public static Block bookshelf;
~ 	public static Block mossy_cobblestone;
~ 	public static Block obsidian;
~ 	public static Block torch;
~ 	public static BlockFire fire;
~ 	public static Block mob_spawner;
~ 	public static Block oak_stairs;
~ 	public static BlockChest chest;
~ 	public static BlockRedstoneWire redstone_wire;
~ 	public static Block diamond_ore;
~ 	public static Block diamond_block;
~ 	public static Block crafting_table;
~ 	public static Block wheat;
~ 	public static Block farmland;
~ 	public static Block furnace;
~ 	public static Block lit_furnace;
~ 	public static Block standing_sign;
~ 	public static Block oak_door;
~ 	public static Block spruce_door;
~ 	public static Block birch_door;
~ 	public static Block jungle_door;
~ 	public static Block acacia_door;
~ 	public static Block dark_oak_door;
~ 	public static Block ladder;
~ 	public static Block rail;
~ 	public static Block stone_stairs;
~ 	public static Block wall_sign;
~ 	public static Block lever;
~ 	public static Block stone_pressure_plate;
~ 	public static Block iron_door;
~ 	public static Block wooden_pressure_plate;
~ 	public static Block redstone_ore;
~ 	public static Block lit_redstone_ore;
~ 	public static Block unlit_redstone_torch;
~ 	public static Block redstone_torch;
~ 	public static Block stone_button;
~ 	public static Block snow_layer;
~ 	public static Block ice;
~ 	public static Block snow;
~ 	public static BlockCactus cactus;
~ 	public static Block clay;
~ 	public static BlockReed reeds;
~ 	public static Block jukebox;
~ 	public static Block oak_fence;
~ 	public static Block spruce_fence;
~ 	public static Block birch_fence;
~ 	public static Block jungle_fence;
~ 	public static Block dark_oak_fence;
~ 	public static Block acacia_fence;
~ 	public static Block pumpkin;
~ 	public static Block netherrack;
~ 	public static Block soul_sand;
~ 	public static Block glowstone;
~ 	public static BlockPortal portal;
~ 	public static Block lit_pumpkin;
~ 	public static Block cake;
~ 	public static BlockRedstoneRepeater unpowered_repeater;
~ 	public static BlockRedstoneRepeater powered_repeater;
~ 	public static Block trapdoor;
~ 	public static Block monster_egg;
~ 	public static Block stonebrick;
~ 	public static Block brown_mushroom_block;
~ 	public static Block red_mushroom_block;
~ 	public static Block iron_bars;
~ 	public static Block glass_pane;
~ 	public static Block melon_block;
~ 	public static Block pumpkin_stem;
~ 	public static Block melon_stem;
~ 	public static Block vine;
~ 	public static Block oak_fence_gate;
~ 	public static Block spruce_fence_gate;
~ 	public static Block birch_fence_gate;
~ 	public static Block jungle_fence_gate;
~ 	public static Block dark_oak_fence_gate;
~ 	public static Block acacia_fence_gate;
~ 	public static Block brick_stairs;
~ 	public static Block stone_brick_stairs;
~ 	public static BlockMycelium mycelium;
~ 	public static Block waterlily;
~ 	public static Block nether_brick;
~ 	public static Block nether_brick_fence;
~ 	public static Block nether_brick_stairs;
~ 	public static Block nether_wart;
~ 	public static Block enchanting_table;
~ 	public static Block brewing_stand;
~ 	public static BlockCauldron cauldron;
~ 	public static Block end_portal;
~ 	public static Block end_portal_frame;
~ 	public static Block end_stone;
~ 	public static Block dragon_egg;
~ 	public static Block redstone_lamp;
~ 	public static Block lit_redstone_lamp;
~ 	public static BlockSlab double_wooden_slab;
~ 	public static BlockSlab wooden_slab;
~ 	public static Block cocoa;
~ 	public static Block sandstone_stairs;
~ 	public static Block emerald_ore;
~ 	public static Block ender_chest;
~ 	public static BlockTripWireHook tripwire_hook;
~ 	public static Block tripwire;
~ 	public static Block emerald_block;
~ 	public static Block spruce_stairs;
~ 	public static Block birch_stairs;
~ 	public static Block jungle_stairs;
~ 	public static Block command_block;
~ 	public static BlockBeacon beacon;
~ 	public static Block cobblestone_wall;
~ 	public static Block flower_pot;
~ 	public static Block carrots;
~ 	public static Block potatoes;
~ 	public static Block wooden_button;
~ 	public static BlockSkull skull;
~ 	public static Block anvil;
~ 	public static Block trapped_chest;
~ 	public static Block light_weighted_pressure_plate;
~ 	public static Block heavy_weighted_pressure_plate;
~ 	public static BlockRedstoneComparator unpowered_comparator;
~ 	public static BlockRedstoneComparator powered_comparator;
~ 	public static BlockDaylightDetector daylight_detector;
~ 	public static BlockDaylightDetector daylight_detector_inverted;
~ 	public static Block redstone_block;
~ 	public static Block quartz_ore;
~ 	public static BlockHopper hopper;
~ 	public static Block quartz_block;
~ 	public static Block quartz_stairs;
~ 	public static Block activator_rail;
~ 	public static Block dropper;
~ 	public static Block stained_hardened_clay;
~ 	public static Block concrete;
~ 	public static Block smooth_stone;
~ 	public static Block blackstone;
~ 	public static Block polished_blackstone;
~ 	public static Block polished_blackstone_bricks;
~ 	public static Block cobbled_deepslate;
~ 	public static Block polished_deepslate;
~ 	public static Block deepslate_bricks;
~ 	public static Block deepslate_tiles;
~ 	public static Block end_stone_bricks;
~ 	public static Block quartz_bricks;
~ 	public static Block crying_obsidian;
~ 	public static Block purpur_block;
~ 	public static Block amethyst_block;
~ 	public static Block calcite;
~ 	public static Block tuff;
~ 	public static Block tuff_bricks;
~ 	public static Block polished_tuff;
~ 	public static Block dripstone_block;
~ 	public static Block moss_block;
~ 	public static Block mud;
~ 	public static Block packed_mud;
~ 	public static Block mud_bricks;
~ 	public static Block smooth_basalt;
~ 	public static Block netherite_block;
~ 	public static Block raw_iron_block;
~ 	public static Block raw_copper_block;
~ 	public static Block raw_gold_block;
~ 	public static Block copper_block;
~ 	public static Block exposed_copper;
~ 	public static Block weathered_copper;
~ 	public static Block oxidized_copper;
~ 	public static Block chiseled_copper;
~ 	public static Block cut_copper;
~ 	public static Block exposed_cut_copper;
~ 	public static Block weathered_cut_copper;
~ 	public static Block oxidized_cut_copper;
~ 	public static Block honeycomb_block;
~ 	public static Block nether_wart_block;
~ 	public static Block warped_wart_block;
~ 	public static Block shroomlight;
~ 	public static Block soul_soil;
~ 	public static Block gilded_blackstone;
~ 	public static Block chiseled_polished_blackstone;
~ 	public static Block cracked_polished_blackstone_bricks;
~ 	public static Block chiseled_deepslate;
~ 	public static Block cracked_deepslate_bricks;
~ 	public static Block cracked_deepslate_tiles;
~ 	public static Block chiseled_nether_bricks;
~ 	public static Block cracked_nether_bricks;
~ 	public static Block red_nether_bricks;
~ 	public static Block blue_ice;
~ 	public static Block sculk;
~ 	public static Block crimson_planks;
~ 	public static Block warped_planks;
~ 	public static Block mangrove_planks;
~ 	public static Block cherry_planks;
~ 	public static Block bamboo_planks;
~ 	public static Block pale_oak_planks;
~ 	public static Block resin_block;
~ 	public static Block resin_bricks;
~ 	public static Block chiseled_resin_bricks;
~ 	public static Block prismarine_bricks;
~ 	public static Block deepslate;
~ 	public static Block basalt;
~ 	public static Block crimson_stem;
~ 	public static Block warped_stem;
~ 	public static Block mangrove_log;
~ 	public static Block cherry_log;
~ 	public static Block purpur_pillar;
~ 	public static Block ochre_froglight;
~ 	public static Block verdant_froglight;
~ 	public static Block pearlescent_froglight;
~ 	public static Block bone_block;
~ 	public static Block bamboo_block;
~ 	public static Block concrete_powder;
~ 	public static Block copper_ore;
~ 	public static Block deepslate_copper_ore;
~ 	public static Block deepslate_coal_ore;
~ 	public static Block deepslate_iron_ore;
~ 	public static Block deepslate_gold_ore;
~ 	public static Block deepslate_diamond_ore;
~ 	public static Block deepslate_redstone_ore;
~ 	public static Block deepslate_lapis_ore;
~ 	public static Block deepslate_emerald_ore;
~ 	public static Block chiseled_tuff;
~ 	public static Block exposed_chiseled_copper;
~ 	public static Block weathered_chiseled_copper;
~ 	public static Block oxidized_chiseled_copper;
~ 	public static Block copper_grate;
~ 	public static Block exposed_copper_grate;
~ 	public static Block weathered_copper_grate;
~ 	public static Block oxidized_copper_grate;
~ 	public static Block copper_bulb;
~ 	public static Block exposed_copper_bulb;
~ 	public static Block weathered_copper_bulb;
~ 	public static Block oxidized_copper_bulb;
~ 	public static Block white_glazed_terracotta;
~ 	public static Block orange_glazed_terracotta;
~ 	public static Block magenta_glazed_terracotta;
~ 	public static Block light_blue_glazed_terracotta;
~ 	public static Block yellow_glazed_terracotta;
~ 	public static Block lime_glazed_terracotta;
~ 	public static Block pink_glazed_terracotta;
~ 	public static Block gray_glazed_terracotta;
~ 	public static Block light_gray_glazed_terracotta;
~ 	public static Block cyan_glazed_terracotta;
~ 	public static Block purple_glazed_terracotta;
~ 	public static Block blue_glazed_terracotta;
~ 	public static Block brown_glazed_terracotta;
~ 	public static Block green_glazed_terracotta;
~ 	public static Block red_glazed_terracotta;
~ 	public static Block black_glazed_terracotta;
~ 	public static Block tube_coral_block;
~ 	public static Block dead_tube_coral_block;
~ 	public static Block brain_coral_block;
~ 	public static Block dead_brain_coral_block;
~ 	public static Block bubble_coral_block;
~ 	public static Block dead_bubble_coral_block;
~ 	public static Block fire_coral_block;
~ 	public static Block dead_fire_coral_block;
~ 	public static Block horn_coral_block;
~ 	public static Block dead_horn_coral_block;
~ 	public static Block nether_gold_ore;
~ 	public static Block bamboo_mosaic;
~ 	public static Block chiseled_red_sandstone;
~ 	public static Block cut_red_sandstone;
~ 	public static Block rooted_dirt;
~ 	public static Block chiseled_tuff_bricks;
~ 	public static Block budding_amethyst;
~ 	public static Block ancient_debris;
~ 	public static Block polished_basalt;
~ 	public static Block magma_block;
~ 	public static Block dark_prismarine;
~ 	public static Block pale_moss_block;
~ 	public static Block reinforced_deepslate;
~ 	public static Block coarse_dirt;
~ 	public static Block wet_sponge;
~ 	public static Block target;
~ 	public static Block note_block;
~ 	public static Block podzol;
~ 	public static Block dried_kelp_block;
~ 	public static Block mangrove_roots;
~ 	public static Block muddy_mangrove_roots;
~ 	public static Block lodestone;
~ 	public static Block chiseled_quartz_block;
~ 	public static Block stone_bricks;
~ 	public static Block mossy_stone_bricks;
~ 	public static Block cracked_stone_bricks;
~ 	public static Block chiseled_stone_bricks;
~ 	public static Block andesite;
~ 	public static Block diorite;
~ 	public static Block granite;
~ 	public static Block polished_andesite;
~ 	public static Block polished_diorite;
~ 	public static Block polished_granite;
~ 	public static Block terracotta;
~ 	public static Block white_terracotta;
~ 	public static Block orange_terracotta;
~ 	public static Block magenta_terracotta;
~ 	public static Block light_blue_terracotta;
~ 	public static Block yellow_terracotta;
~ 	public static Block lime_terracotta;
~ 	public static Block pink_terracotta;
~ 	public static Block gray_terracotta;
~ 	public static Block light_gray_terracotta;
~ 	public static Block cyan_terracotta;
~ 	public static Block purple_terracotta;
~ 	public static Block blue_terracotta;
~ 	public static Block brown_terracotta;
~ 	public static Block green_terracotta;
~ 	public static Block red_terracotta;
~ 	public static Block black_terracotta;
~ 	public static Block stripped_oak_log;
~ 	public static Block stripped_spruce_log;
~ 	public static Block stripped_birch_log;
~ 	public static Block stripped_jungle_log;
~ 	public static Block stripped_acacia_log;
~ 	public static Block stripped_dark_oak_log;
~ 	public static Block stripped_mangrove_log;
~ 	public static Block stripped_cherry_log;
~ 	public static Block stripped_crimson_stem;
~ 	public static Block stripped_warped_stem;
~ 	public static Block stripped_bamboo_block;
~ 	public static Block crimson_nylium;
~ 	public static Block warped_nylium;
~ 	public static Block melon;
~ 	public static Block carved_pumpkin;
~ 	public static Block jack_o_lantern;
~ 	public static Block cut_sandstone;
~ 	public static Block chiseled_sandstone;
~ 	public static Block red_sand;
~ 	public static Block chiseled_bookshelf_empty;

> INSERT  1 : 23  @  1

+ 	public static Block barrier;
+ 	public static Block iron_trapdoor;
+ 	public static Block hay_block;
+ 	public static Block carpet;
+ 	public static Block hardened_clay;
+ 	public static Block coal_block;
+ 	public static Block packed_ice;
+ 	public static Block acacia_stairs;
+ 	public static Block dark_oak_stairs;
+ 	public static Block slime_block;
+ 	public static BlockDoublePlant double_plant;
+ 	public static BlockStainedGlass stained_glass;
+ 	public static BlockStainedGlassPane stained_glass_pane;
+ 	public static Block prismarine;
+ 	public static Block sea_lantern;
+ 	public static Block standing_banner;
+ 	public static Block wall_banner;
+ 	public static Block red_sandstone;
+ 	public static Block red_sandstone_stairs;
+ 	public static BlockSlab double_stone_slab2;
+ 	public static BlockSlab stone_slab2;
+ 

> CHANGE  4 : 5  @  4 : 5

~ 	static void doBootstrap() {

> INSERT  180 : 374  @  180

+ 			concrete = getRegisteredBlock("concrete");
+ 			smooth_stone = getRegisteredBlock("smooth_stone");
+ 			blackstone = getRegisteredBlock("blackstone");
+ 			polished_blackstone = getRegisteredBlock("polished_blackstone");
+ 			polished_blackstone_bricks = getRegisteredBlock("polished_blackstone_bricks");
+ 			cobbled_deepslate = getRegisteredBlock("cobbled_deepslate");
+ 			polished_deepslate = getRegisteredBlock("polished_deepslate");
+ 			deepslate_bricks = getRegisteredBlock("deepslate_bricks");
+ 			deepslate_tiles = getRegisteredBlock("deepslate_tiles");
+ 			end_stone_bricks = getRegisteredBlock("end_stone_bricks");
+ 			quartz_bricks = getRegisteredBlock("quartz_bricks");
+ 			crying_obsidian = getRegisteredBlock("crying_obsidian");
+ 			purpur_block = getRegisteredBlock("purpur_block");
+ 			amethyst_block = getRegisteredBlock("amethyst_block");
+ 			calcite = getRegisteredBlock("calcite");
+ 			tuff = getRegisteredBlock("tuff");
+ 			tuff_bricks = getRegisteredBlock("tuff_bricks");
+ 			polished_tuff = getRegisteredBlock("polished_tuff");
+ 			dripstone_block = getRegisteredBlock("dripstone_block");
+ 			moss_block = getRegisteredBlock("moss_block");
+ 			mud = getRegisteredBlock("mud");
+ 			packed_mud = getRegisteredBlock("packed_mud");
+ 			mud_bricks = getRegisteredBlock("mud_bricks");
+ 			smooth_basalt = getRegisteredBlock("smooth_basalt");
+ 			netherite_block = getRegisteredBlock("netherite_block");
+ 			raw_iron_block = getRegisteredBlock("raw_iron_block");
+ 			raw_copper_block = getRegisteredBlock("raw_copper_block");
+ 			raw_gold_block = getRegisteredBlock("raw_gold_block");
+ 			copper_block = getRegisteredBlock("copper_block");
+ 			exposed_copper = getRegisteredBlock("exposed_copper");
+ 			weathered_copper = getRegisteredBlock("weathered_copper");
+ 			oxidized_copper = getRegisteredBlock("oxidized_copper");
+ 			chiseled_copper = getRegisteredBlock("chiseled_copper");
+ 			cut_copper = getRegisteredBlock("cut_copper");
+ 			exposed_cut_copper = getRegisteredBlock("exposed_cut_copper");
+ 			weathered_cut_copper = getRegisteredBlock("weathered_cut_copper");
+ 			oxidized_cut_copper = getRegisteredBlock("oxidized_cut_copper");
+ 			honeycomb_block = getRegisteredBlock("honeycomb_block");
+ 			nether_wart_block = getRegisteredBlock("nether_wart_block");
+ 			warped_wart_block = getRegisteredBlock("warped_wart_block");
+ 			shroomlight = getRegisteredBlock("shroomlight");
+ 			soul_soil = getRegisteredBlock("soul_soil");
+ 			gilded_blackstone = getRegisteredBlock("gilded_blackstone");
+ 			chiseled_polished_blackstone = getRegisteredBlock("chiseled_polished_blackstone");
+ 			cracked_polished_blackstone_bricks = getRegisteredBlock("cracked_polished_blackstone_bricks");
+ 			chiseled_deepslate = getRegisteredBlock("chiseled_deepslate");
+ 			cracked_deepslate_bricks = getRegisteredBlock("cracked_deepslate_bricks");
+ 			cracked_deepslate_tiles = getRegisteredBlock("cracked_deepslate_tiles");
+ 			chiseled_nether_bricks = getRegisteredBlock("chiseled_nether_bricks");
+ 			cracked_nether_bricks = getRegisteredBlock("cracked_nether_bricks");
+ 			red_nether_bricks = getRegisteredBlock("red_nether_bricks");
+ 			blue_ice = getRegisteredBlock("blue_ice");
+ 			sculk = getRegisteredBlock("sculk");
+ 			crimson_planks = getRegisteredBlock("crimson_planks");
+ 			warped_planks = getRegisteredBlock("warped_planks");
+ 			mangrove_planks = getRegisteredBlock("mangrove_planks");
+ 			cherry_planks = getRegisteredBlock("cherry_planks");
+ 			bamboo_planks = getRegisteredBlock("bamboo_planks");
+ 			pale_oak_planks = getRegisteredBlock("pale_oak_planks");
+ 			resin_block = getRegisteredBlock("resin_block");
+ 			resin_bricks = getRegisteredBlock("resin_bricks");
+ 			chiseled_resin_bricks = getRegisteredBlock("chiseled_resin_bricks");
+ 			prismarine_bricks = getRegisteredBlock("prismarine_bricks");
+ 			deepslate = getRegisteredBlock("deepslate");
+ 			basalt = getRegisteredBlock("basalt");
+ 			crimson_stem = getRegisteredBlock("crimson_stem");
+ 			warped_stem = getRegisteredBlock("warped_stem");
+ 			mangrove_log = getRegisteredBlock("mangrove_log");
+ 			cherry_log = getRegisteredBlock("cherry_log");
+ 			purpur_pillar = getRegisteredBlock("purpur_pillar");
+ 			ochre_froglight = getRegisteredBlock("ochre_froglight");
+ 			verdant_froglight = getRegisteredBlock("verdant_froglight");
+ 			pearlescent_froglight = getRegisteredBlock("pearlescent_froglight");
+ 			bone_block = getRegisteredBlock("bone_block");
+ 			bamboo_block = getRegisteredBlock("bamboo_block");
+ 			concrete_powder = getRegisteredBlock("concrete_powder");
+ 			copper_ore = getRegisteredBlock("copper_ore");
+ 			deepslate_copper_ore = getRegisteredBlock("deepslate_copper_ore");
+ 			deepslate_coal_ore = getRegisteredBlock("deepslate_coal_ore");
+ 			deepslate_iron_ore = getRegisteredBlock("deepslate_iron_ore");
+ 			deepslate_gold_ore = getRegisteredBlock("deepslate_gold_ore");
+ 			deepslate_diamond_ore = getRegisteredBlock("deepslate_diamond_ore");
+ 			deepslate_redstone_ore = getRegisteredBlock("deepslate_redstone_ore");
+ 			deepslate_lapis_ore = getRegisteredBlock("deepslate_lapis_ore");
+ 			deepslate_emerald_ore = getRegisteredBlock("deepslate_emerald_ore");
+ 			chiseled_tuff = getRegisteredBlock("chiseled_tuff");
+ 			exposed_chiseled_copper = getRegisteredBlock("exposed_chiseled_copper");
+ 			weathered_chiseled_copper = getRegisteredBlock("weathered_chiseled_copper");
+ 			oxidized_chiseled_copper = getRegisteredBlock("oxidized_chiseled_copper");
+ 			copper_grate = getRegisteredBlock("copper_grate");
+ 			exposed_copper_grate = getRegisteredBlock("exposed_copper_grate");
+ 			weathered_copper_grate = getRegisteredBlock("weathered_copper_grate");
+ 			oxidized_copper_grate = getRegisteredBlock("oxidized_copper_grate");
+ 			copper_bulb = getRegisteredBlock("copper_bulb");
+ 			exposed_copper_bulb = getRegisteredBlock("exposed_copper_bulb");
+ 			weathered_copper_bulb = getRegisteredBlock("weathered_copper_bulb");
+ 			oxidized_copper_bulb = getRegisteredBlock("oxidized_copper_bulb");
+ 			white_glazed_terracotta = getRegisteredBlock("white_glazed_terracotta");
+ 			orange_glazed_terracotta = getRegisteredBlock("orange_glazed_terracotta");
+ 			magenta_glazed_terracotta = getRegisteredBlock("magenta_glazed_terracotta");
+ 			light_blue_glazed_terracotta = getRegisteredBlock("light_blue_glazed_terracotta");
+ 			yellow_glazed_terracotta = getRegisteredBlock("yellow_glazed_terracotta");
+ 			lime_glazed_terracotta = getRegisteredBlock("lime_glazed_terracotta");
+ 			pink_glazed_terracotta = getRegisteredBlock("pink_glazed_terracotta");
+ 			gray_glazed_terracotta = getRegisteredBlock("gray_glazed_terracotta");
+ 			light_gray_glazed_terracotta = getRegisteredBlock("light_gray_glazed_terracotta");
+ 			cyan_glazed_terracotta = getRegisteredBlock("cyan_glazed_terracotta");
+ 			purple_glazed_terracotta = getRegisteredBlock("purple_glazed_terracotta");
+ 			blue_glazed_terracotta = getRegisteredBlock("blue_glazed_terracotta");
+ 			brown_glazed_terracotta = getRegisteredBlock("brown_glazed_terracotta");
+ 			green_glazed_terracotta = getRegisteredBlock("green_glazed_terracotta");
+ 			red_glazed_terracotta = getRegisteredBlock("red_glazed_terracotta");
+ 			black_glazed_terracotta = getRegisteredBlock("black_glazed_terracotta");
+ 			tube_coral_block = getRegisteredBlock("tube_coral_block");
+ 			dead_tube_coral_block = getRegisteredBlock("dead_tube_coral_block");
+ 			brain_coral_block = getRegisteredBlock("brain_coral_block");
+ 			dead_brain_coral_block = getRegisteredBlock("dead_brain_coral_block");
+ 			bubble_coral_block = getRegisteredBlock("bubble_coral_block");
+ 			dead_bubble_coral_block = getRegisteredBlock("dead_bubble_coral_block");
+ 			fire_coral_block = getRegisteredBlock("fire_coral_block");
+ 			dead_fire_coral_block = getRegisteredBlock("dead_fire_coral_block");
+ 			horn_coral_block = getRegisteredBlock("horn_coral_block");
+ 			dead_horn_coral_block = getRegisteredBlock("dead_horn_coral_block");
+ 			nether_gold_ore = getRegisteredBlock("nether_gold_ore");
+ 			bamboo_mosaic = getRegisteredBlock("bamboo_mosaic");
+ 			chiseled_red_sandstone = getRegisteredBlock("chiseled_red_sandstone");
+ 			cut_red_sandstone = getRegisteredBlock("cut_red_sandstone");
+ 			rooted_dirt = getRegisteredBlock("rooted_dirt");
+ 			chiseled_tuff_bricks = getRegisteredBlock("chiseled_tuff_bricks");
+ 			budding_amethyst = getRegisteredBlock("budding_amethyst");
+ 			ancient_debris = getRegisteredBlock("ancient_debris");
+ 			polished_basalt = getRegisteredBlock("polished_basalt");
+ 			magma_block = getRegisteredBlock("magma_block");
+ 			dark_prismarine = getRegisteredBlock("dark_prismarine");
+ 			pale_moss_block = getRegisteredBlock("pale_moss_block");
+ 			reinforced_deepslate = getRegisteredBlock("reinforced_deepslate");
+ 			coarse_dirt = getRegisteredBlock("coarse_dirt");
+ 			wet_sponge = getRegisteredBlock("wet_sponge");
+ 			target = getRegisteredBlock("target");
+ 			note_block = getRegisteredBlock("note_block");
+ 			podzol = getRegisteredBlock("podzol");
+ 			dried_kelp_block = getRegisteredBlock("dried_kelp_block");
+ 			mangrove_roots = getRegisteredBlock("mangrove_roots");
+ 			muddy_mangrove_roots = getRegisteredBlock("muddy_mangrove_roots");
+ 			lodestone = getRegisteredBlock("lodestone");
+ 			chiseled_quartz_block = getRegisteredBlock("chiseled_quartz_block");
+ 			stone_bricks = getRegisteredBlock("stone_bricks");
+ 			mossy_stone_bricks = getRegisteredBlock("mossy_stone_bricks");
+ 			cracked_stone_bricks = getRegisteredBlock("cracked_stone_bricks");
+ 			chiseled_stone_bricks = getRegisteredBlock("chiseled_stone_bricks");
+ 			andesite = getRegisteredBlock("andesite");
+ 			diorite = getRegisteredBlock("diorite");
+ 			granite = getRegisteredBlock("granite");
+ 			polished_andesite = getRegisteredBlock("polished_andesite");
+ 			polished_diorite = getRegisteredBlock("polished_diorite");
+ 			polished_granite = getRegisteredBlock("polished_granite");
+ 			terracotta = getRegisteredBlock("terracotta");
+ 			white_terracotta = getRegisteredBlock("white_terracotta");
+ 			orange_terracotta = getRegisteredBlock("orange_terracotta");
+ 			magenta_terracotta = getRegisteredBlock("magenta_terracotta");
+ 			light_blue_terracotta = getRegisteredBlock("light_blue_terracotta");
+ 			yellow_terracotta = getRegisteredBlock("yellow_terracotta");
+ 			lime_terracotta = getRegisteredBlock("lime_terracotta");
+ 			pink_terracotta = getRegisteredBlock("pink_terracotta");
+ 			gray_terracotta = getRegisteredBlock("gray_terracotta");
+ 			light_gray_terracotta = getRegisteredBlock("light_gray_terracotta");
+ 			cyan_terracotta = getRegisteredBlock("cyan_terracotta");
+ 			purple_terracotta = getRegisteredBlock("purple_terracotta");
+ 			blue_terracotta = getRegisteredBlock("blue_terracotta");
+ 			brown_terracotta = getRegisteredBlock("brown_terracotta");
+ 			green_terracotta = getRegisteredBlock("green_terracotta");
+ 			red_terracotta = getRegisteredBlock("red_terracotta");
+ 			black_terracotta = getRegisteredBlock("black_terracotta");
+ 			stripped_oak_log = getRegisteredBlock("stripped_oak_log");
+ 			stripped_spruce_log = getRegisteredBlock("stripped_spruce_log");
+ 			stripped_birch_log = getRegisteredBlock("stripped_birch_log");
+ 			stripped_jungle_log = getRegisteredBlock("stripped_jungle_log");
+ 			stripped_acacia_log = getRegisteredBlock("stripped_acacia_log");
+ 			stripped_dark_oak_log = getRegisteredBlock("stripped_dark_oak_log");
+ 			stripped_mangrove_log = getRegisteredBlock("stripped_mangrove_log");
+ 			stripped_cherry_log = getRegisteredBlock("stripped_cherry_log");
+ 			stripped_crimson_stem = getRegisteredBlock("stripped_crimson_stem");
+ 			stripped_warped_stem = getRegisteredBlock("stripped_warped_stem");
+ 			stripped_bamboo_block = getRegisteredBlock("stripped_bamboo_block");
+ 			crimson_nylium = getRegisteredBlock("crimson_nylium");
+ 			warped_nylium = getRegisteredBlock("warped_nylium");
+ 			melon = getRegisteredBlock("melon");
+ 			carved_pumpkin = getRegisteredBlock("carved_pumpkin");
+ 			jack_o_lantern = getRegisteredBlock("jack_o_lantern");
+ 			cut_sandstone = getRegisteredBlock("cut_sandstone");
+ 			chiseled_sandstone = getRegisteredBlock("chiseled_sandstone");
+ 			red_sand = getRegisteredBlock("red_sand");
+ 			chiseled_bookshelf_empty = getRegisteredBlock("chiseled_bookshelf_empty");
+ 

> EOF
