
# Eagler Context Redacted Diff
# Copyright (c) 2026 lax1dude. All rights reserved.

# Version: 1.0
# Author: lax1dude

> DELETE  34  @  34 : 35

> CHANGE  3 : 255  @  3 : 201

~ 	public static Block air;
~ 	public static Block stone;
~ 	public static BlockGrass grass;
~ 	public static Block dirt;
~ 	public static Block cobblestone;
~ 	public static Block planks;
~ 	public static Block sapling;
~ 	public static Block bedrock;
~ 	public static BlockDynamicLiquid flowing_water;
~ 	public static BlockStaticLiquid water;
~ 	public static BlockDynamicLiquid flowing_lava;
~ 	public static BlockStaticLiquid lava;
~ 	public static BlockSand sand;
~ 	public static Block gravel;
~ 	public static Block gold_ore;
~ 	public static Block iron_ore;
~ 	public static Block coal_ore;
~ 	public static Block log;
~ 	public static Block log2;
~ 	public static BlockLeaves leaves;
~ 	public static BlockLeaves leaves2;
~ 	public static Block sponge;
~ 	public static Block glass;
~ 	public static Block lapis_ore;
~ 	public static Block lapis_block;
~ 	public static Block dispenser;
~ 	public static Block sandstone;
~ 	public static Block noteblock;
~ 	public static Block bed;
~ 	public static Block golden_rail;
~ 	public static Block detector_rail;
~ 	public static BlockPistonBase sticky_piston;
~ 	public static Block web;
~ 	public static BlockTallGrass tallgrass;
~ 	public static BlockDeadBush deadbush;
~ 	public static BlockPistonBase piston;
~ 	public static BlockPistonExtension piston_head;
~ 	public static Block wool;
~ 	public static BlockPistonMoving piston_extension;
~ 	public static BlockFlower yellow_flower;
~ 	public static BlockFlower red_flower;
~ 	public static BlockBush brown_mushroom;
~ 	public static BlockBush red_mushroom;
~ 	public static Block gold_block;
~ 	public static Block iron_block;
~ 	public static BlockSlab double_stone_slab;
~ 	public static BlockSlab stone_slab;
~ 	public static Block brick_block;
~ 	public static Block tnt;
~ 	public static Block bookshelf;
~ 	public static Block mossy_cobblestone;
~ 	public static Block obsidian;
~ 	public static Block torch;
~ 	public static BlockFire fire;
~ 	public static Block mob_spawner;
~ 	public static Block oak_stairs;
~ 	public static BlockChest chest;
~ 	public static BlockRedstoneWire redstone_wire;
~ 	public static Block diamond_ore;
~ 	public static Block diamond_block;
~ 	public static Block crafting_table;
~ 	public static Block wheat;
~ 	public static Block farmland;
~ 	public static Block furnace;
~ 	public static Block lit_furnace;
~ 	public static Block standing_sign;
~ 	public static Block oak_door;
~ 	public static Block spruce_door;
~ 	public static Block birch_door;
~ 	public static Block jungle_door;
~ 	public static Block acacia_door;
~ 	public static Block dark_oak_door;
~ 	public static Block ladder;
~ 	public static Block rail;
~ 	public static Block stone_stairs;
~ 	public static Block wall_sign;
~ 	public static Block lever;
~ 	public static Block stone_pressure_plate;
~ 	public static Block iron_door;
~ 	public static Block wooden_pressure_plate;
~ 	public static Block redstone_ore;
~ 	public static Block lit_redstone_ore;
~ 	public static Block unlit_redstone_torch;
~ 	public static Block redstone_torch;
~ 	public static Block stone_button;
~ 	public static Block snow_layer;
~ 	public static Block ice;
~ 	public static Block snow;
~ 	public static BlockCactus cactus;
~ 	public static Block clay;
~ 	public static BlockReed reeds;
~ 	public static Block jukebox;
~ 	public static Block oak_fence;
~ 	public static Block spruce_fence;
~ 	public static Block birch_fence;
~ 	public static Block jungle_fence;
~ 	public static Block dark_oak_fence;
~ 	public static Block acacia_fence;
~ 	public static Block pumpkin;
~ 	public static Block netherrack;
~ 	public static Block soul_sand;
~ 	public static Block glowstone;
~ 	public static BlockPortal portal;
~ 	public static Block lit_pumpkin;
~ 	public static Block cake;
~ 	public static BlockRedstoneRepeater unpowered_repeater;
~ 	public static BlockRedstoneRepeater powered_repeater;
~ 	public static Block trapdoor;
~ 	public static Block monster_egg;
~ 	public static Block stonebrick;
~ 	public static Block brown_mushroom_block;
~ 	public static Block red_mushroom_block;
~ 	public static Block iron_bars;
~ 	public static Block glass_pane;
~ 	public static Block melon_block;
~ 	public static Block pumpkin_stem;
~ 	public static Block melon_stem;
~ 	public static Block vine;
~ 	public static Block oak_fence_gate;
~ 	public static Block spruce_fence_gate;
~ 	public static Block birch_fence_gate;
~ 	public static Block jungle_fence_gate;
~ 	public static Block dark_oak_fence_gate;
~ 	public static Block acacia_fence_gate;
~ 	public static Block brick_stairs;
~ 	public static Block stone_brick_stairs;
~ 	public static BlockMycelium mycelium;
~ 	public static Block waterlily;
~ 	public static Block nether_brick;
~ 	public static Block nether_brick_fence;
~ 	public static Block nether_brick_stairs;
~ 	public static Block nether_wart;
~ 	public static Block enchanting_table;
~ 	public static Block brewing_stand;
~ 	public static BlockCauldron cauldron;
~ 	public static Block end_portal;
~ 	public static Block end_portal_frame;
~ 	public static Block end_stone;
~ 	public static Block dragon_egg;
~ 	public static Block redstone_lamp;
~ 	public static Block lit_redstone_lamp;
~ 	public static BlockSlab double_wooden_slab;
~ 	public static BlockSlab wooden_slab;
~ 	public static Block cocoa;
~ 	public static Block sandstone_stairs;
~ 	public static Block emerald_ore;
~ 	public static Block ender_chest;
~ 	public static BlockTripWireHook tripwire_hook;
~ 	public static Block tripwire;
~ 	public static Block emerald_block;
~ 	public static Block spruce_stairs;
~ 	public static Block birch_stairs;
~ 	public static Block jungle_stairs;
~ 	public static Block command_block;
~ 	public static BlockBeacon beacon;
~ 	public static Block cobblestone_wall;
~ 	public static Block flower_pot;
~ 	public static Block carrots;
~ 	public static Block potatoes;
~ 	public static Block wooden_button;
~ 	public static BlockSkull skull;
~ 	public static Block anvil;
~ 	public static Block trapped_chest;
~ 	public static Block light_weighted_pressure_plate;
~ 	public static Block heavy_weighted_pressure_plate;
~ 	public static BlockRedstoneComparator unpowered_comparator;
~ 	public static BlockRedstoneComparator powered_comparator;
~ 	public static BlockDaylightDetector daylight_detector;
~ 	public static BlockDaylightDetector daylight_detector_inverted;
~ 	public static Block redstone_block;
~ 	public static Block quartz_ore;
~ 	public static BlockHopper hopper;
~ 	public static Block quartz_block;
~ 	public static Block quartz_stairs;
~ 	public static Block activator_rail;
~ 	public static Block dropper;
~ 	public static Block stained_hardened_clay;
~ 	public static Block concrete;
~ 	public static Block smooth_stone;
~ 	public static Block blackstone;
~ 	public static Block polished_blackstone;
~ 	public static Block polished_blackstone_bricks;
~ 	public static Block cobbled_deepslate;
~ 	public static Block polished_deepslate;
~ 	public static Block deepslate_bricks;
~ 	public static Block deepslate_tiles;
~ 	public static Block end_stone_bricks;
~ 	public static Block quartz_bricks;
~ 	public static Block crying_obsidian;
~ 	public static Block purpur_block;
~ 	public static Block amethyst_block;
~ 	public static Block calcite;
~ 	public static Block tuff;
~ 	public static Block tuff_bricks;
~ 	public static Block polished_tuff;
~ 	public static Block dripstone_block;
~ 	public static Block moss_block;
~ 	public static Block mud;
~ 	public static Block packed_mud;
~ 	public static Block mud_bricks;
~ 	public static Block smooth_basalt;
~ 	public static Block netherite_block;
~ 	public static Block raw_iron_block;
~ 	public static Block raw_copper_block;
~ 	public static Block raw_gold_block;
~ 	public static Block copper_block;
~ 	public static Block exposed_copper;
~ 	public static Block weathered_copper;
~ 	public static Block oxidized_copper;
~ 	public static Block chiseled_copper;
~ 	public static Block cut_copper;
~ 	public static Block exposed_cut_copper;
~ 	public static Block weathered_cut_copper;
~ 	public static Block oxidized_cut_copper;
~ 	public static Block honeycomb_block;
~ 	public static Block nether_wart_block;
~ 	public static Block warped_wart_block;
~ 	public static Block shroomlight;
~ 	public static Block soul_soil;
~ 	public static Block gilded_blackstone;
~ 	public static Block chiseled_polished_blackstone;
~ 	public static Block cracked_polished_blackstone_bricks;
~ 	public static Block chiseled_deepslate;
~ 	public static Block cracked_deepslate_bricks;
~ 	public static Block cracked_deepslate_tiles;
~ 	public static Block chiseled_nether_bricks;
~ 	public static Block cracked_nether_bricks;
~ 	public static Block red_nether_bricks;
~ 	public static Block blue_ice;
~ 	public static Block sculk;
~ 	public static Block crimson_planks;
~ 	public static Block warped_planks;
~ 	public static Block mangrove_planks;
~ 	public static Block cherry_planks;
~ 	public static Block bamboo_planks;
~ 	public static Block pale_oak_planks;
~ 	public static Block resin_block;
~ 	public static Block resin_bricks;
~ 	public static Block chiseled_resin_bricks;
~ 	public static Block prismarine_bricks;
~ 	public static Block deepslate;
~ 	public static Block basalt;
~ 	public static Block crimson_stem;
~ 	public static Block warped_stem;
~ 	public static Block mangrove_log;
~ 	public static Block cherry_log;
~ 	public static Block purpur_pillar;
~ 	public static Block ochre_froglight;
~ 	public static Block verdant_froglight;
~ 	public static Block pearlescent_froglight;
~ 	public static Block bone_block;
~ 	public static Block bamboo_block;

> INSERT  1 : 23  @  1

+ 	public static Block barrier;
+ 	public static Block iron_trapdoor;
+ 	public static Block hay_block;
+ 	public static Block carpet;
+ 	public static Block hardened_clay;
+ 	public static Block coal_block;
+ 	public static Block packed_ice;
+ 	public static Block acacia_stairs;
+ 	public static Block dark_oak_stairs;
+ 	public static Block slime_block;
+ 	public static BlockDoublePlant double_plant;
+ 	public static BlockStainedGlass stained_glass;
+ 	public static BlockStainedGlassPane stained_glass_pane;
+ 	public static Block prismarine;
+ 	public static Block sea_lantern;
+ 	public static Block standing_banner;
+ 	public static Block wall_banner;
+ 	public static Block red_sandstone;
+ 	public static Block red_sandstone_stairs;
+ 	public static BlockSlab double_stone_slab2;
+ 	public static BlockSlab stone_slab2;
+ 

> CHANGE  4 : 5  @  4 : 5

~ 	static void doBootstrap() {

> INSERT  180 : 256  @  180

+ 			concrete = getRegisteredBlock("concrete");
+ 			smooth_stone = getRegisteredBlock("smooth_stone");
+ 			blackstone = getRegisteredBlock("blackstone");
+ 			polished_blackstone = getRegisteredBlock("polished_blackstone");
+ 			polished_blackstone_bricks = getRegisteredBlock("polished_blackstone_bricks");
+ 			cobbled_deepslate = getRegisteredBlock("cobbled_deepslate");
+ 			polished_deepslate = getRegisteredBlock("polished_deepslate");
+ 			deepslate_bricks = getRegisteredBlock("deepslate_bricks");
+ 			deepslate_tiles = getRegisteredBlock("deepslate_tiles");
+ 			end_stone_bricks = getRegisteredBlock("end_stone_bricks");
+ 			quartz_bricks = getRegisteredBlock("quartz_bricks");
+ 			crying_obsidian = getRegisteredBlock("crying_obsidian");
+ 			purpur_block = getRegisteredBlock("purpur_block");
+ 			amethyst_block = getRegisteredBlock("amethyst_block");
+ 			calcite = getRegisteredBlock("calcite");
+ 			tuff = getRegisteredBlock("tuff");
+ 			tuff_bricks = getRegisteredBlock("tuff_bricks");
+ 			polished_tuff = getRegisteredBlock("polished_tuff");
+ 			dripstone_block = getRegisteredBlock("dripstone_block");
+ 			moss_block = getRegisteredBlock("moss_block");
+ 			mud = getRegisteredBlock("mud");
+ 			packed_mud = getRegisteredBlock("packed_mud");
+ 			mud_bricks = getRegisteredBlock("mud_bricks");
+ 			smooth_basalt = getRegisteredBlock("smooth_basalt");
+ 			netherite_block = getRegisteredBlock("netherite_block");
+ 			raw_iron_block = getRegisteredBlock("raw_iron_block");
+ 			raw_copper_block = getRegisteredBlock("raw_copper_block");
+ 			raw_gold_block = getRegisteredBlock("raw_gold_block");
+ 			copper_block = getRegisteredBlock("copper_block");
+ 			exposed_copper = getRegisteredBlock("exposed_copper");
+ 			weathered_copper = getRegisteredBlock("weathered_copper");
+ 			oxidized_copper = getRegisteredBlock("oxidized_copper");
+ 			chiseled_copper = getRegisteredBlock("chiseled_copper");
+ 			cut_copper = getRegisteredBlock("cut_copper");
+ 			exposed_cut_copper = getRegisteredBlock("exposed_cut_copper");
+ 			weathered_cut_copper = getRegisteredBlock("weathered_cut_copper");
+ 			oxidized_cut_copper = getRegisteredBlock("oxidized_cut_copper");
+ 			honeycomb_block = getRegisteredBlock("honeycomb_block");
+ 			nether_wart_block = getRegisteredBlock("nether_wart_block");
+ 			warped_wart_block = getRegisteredBlock("warped_wart_block");
+ 			shroomlight = getRegisteredBlock("shroomlight");
+ 			soul_soil = getRegisteredBlock("soul_soil");
+ 			gilded_blackstone = getRegisteredBlock("gilded_blackstone");
+ 			chiseled_polished_blackstone = getRegisteredBlock("chiseled_polished_blackstone");
+ 			cracked_polished_blackstone_bricks = getRegisteredBlock("cracked_polished_blackstone_bricks");
+ 			chiseled_deepslate = getRegisteredBlock("chiseled_deepslate");
+ 			cracked_deepslate_bricks = getRegisteredBlock("cracked_deepslate_bricks");
+ 			cracked_deepslate_tiles = getRegisteredBlock("cracked_deepslate_tiles");
+ 			chiseled_nether_bricks = getRegisteredBlock("chiseled_nether_bricks");
+ 			cracked_nether_bricks = getRegisteredBlock("cracked_nether_bricks");
+ 			red_nether_bricks = getRegisteredBlock("red_nether_bricks");
+ 			blue_ice = getRegisteredBlock("blue_ice");
+ 			sculk = getRegisteredBlock("sculk");
+ 			crimson_planks = getRegisteredBlock("crimson_planks");
+ 			warped_planks = getRegisteredBlock("warped_planks");
+ 			mangrove_planks = getRegisteredBlock("mangrove_planks");
+ 			cherry_planks = getRegisteredBlock("cherry_planks");
+ 			bamboo_planks = getRegisteredBlock("bamboo_planks");
+ 			pale_oak_planks = getRegisteredBlock("pale_oak_planks");
+ 			resin_block = getRegisteredBlock("resin_block");
+ 			resin_bricks = getRegisteredBlock("resin_bricks");
+ 			chiseled_resin_bricks = getRegisteredBlock("chiseled_resin_bricks");
+ 			prismarine_bricks = getRegisteredBlock("prismarine_bricks");
+ 			deepslate = getRegisteredBlock("deepslate");
+ 			basalt = getRegisteredBlock("basalt");
+ 			crimson_stem = getRegisteredBlock("crimson_stem");
+ 			warped_stem = getRegisteredBlock("warped_stem");
+ 			mangrove_log = getRegisteredBlock("mangrove_log");
+ 			cherry_log = getRegisteredBlock("cherry_log");
+ 			purpur_pillar = getRegisteredBlock("purpur_pillar");
+ 			ochre_froglight = getRegisteredBlock("ochre_froglight");
+ 			verdant_froglight = getRegisteredBlock("verdant_froglight");
+ 			pearlescent_froglight = getRegisteredBlock("pearlescent_froglight");
+ 			bone_block = getRegisteredBlock("bone_block");
+ 			bamboo_block = getRegisteredBlock("bamboo_block");
+ 

> EOF
